version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  celery:
    build: ./backend
    command: celery -A foodgram worker -l INFO
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  celery-beat:
    build: ./backend
    command: celery -A foodgram beat -l INFO
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis

volumes:
  postgres_data: 